# Generated by Django 2.0.5 on 2018-05-26 19:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=35)),
                ('hash160', models.CharField(max_length=54)),
                ('no_transactions', models.IntegerField()),
                ('received', models.BigIntegerField()),
                ('sent', models.BigIntegerField()),
                ('balance', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=256)),
                ('tx_inputs', django.contrib.postgres.fields.jsonb.JSONField()),
                ('tx_outs', django.contrib.postgres.fields.jsonb.JSONField()),
                ('timestamp', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='transactions',
            field=models.ManyToManyField(to='address_info.Transaction'),
        ),
    ]
