# Generated by Django 2.0.5 on 2018-05-25 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address_info', '0002_auto_20180524_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='inputs',
            new_name='tx_json',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='outputs',
        ),
    ]
